var price1 = 20;
console.log(typeof price1);
var price2 = "400" ;
console.log(typeof price2);
var happy = true ;
console.log(typeof happy);
var price4;
console.log(price4);
var num1  = 0.2 ;
var num2 = 0.3 ;
var total = num1 +  num2 ;
console.log(total);